# Generated by Django 4.0.4 on 2022-05-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_collider', '0002_remove_stock_pick_created_remove_stock_pick_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_pick',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
