# Generated by Django 4.0.4 on 2022-05-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trend_collider', '0003_stock_pick_description'),
    ]

    operations = [
    ]
