# Generated by Django 4.0.4 on 2022-05-12 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trend_collider', '0005_alter_stock_pick_symbol'),
        ('trend_collider', '0006_auto_20220512_1605'),
    ]

    operations = [
    ]
