# Generated by Django 4.0.4 on 2022-05-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_collider', '0009_remove_stock_pick_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_pick',
            name='symbol',
            field=models.CharField(max_length=15),
        ),
    ]
