# Generated by Django 4.0.4 on 2022-05-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_collider', '0010_alter_stock_pick_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_pick',
            name='description',
            field=models.CharField(default='description', max_length=150),
            preserve_default=False,
        ),
    ]
