# Generated by Django 4.0.4 on 2022-05-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_collider', '0013_remove_weigh_in_weight_in_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weigh_in',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
