# Generated by Django 4.0.4 on 2022-05-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_collider', '0014_alter_weigh_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weigh_in',
            name='date',
            field=models.DateField(),
        ),
    ]
